updated

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -12,6 +12,9 @@ jobs:
     - name: Init
       run: |
         echo -e "machine github.com\nlogin zmaplex\npassword ${{secrets.MY_GITHUB_TOKEN}}" > ~/.netrc
+        mkdir -p /etc/sing-box-pro
+        curl ${{secrets.SING_BOX_PRO_CONFIG_URL}} -o /etc/sing-box-pro/server.json
+
     - name: Checkout code
       uses: actions/checkout@v4
       with:
@@ -32,6 +35,23 @@ jobs:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-southeast-1
+
+    - name: Check Netflix response
+      run: |
+        chmod a+x sing-box
+        ./sing-box run -c /etc/sing-box-pro/server.json &
+        response=$(curl -o /dev/null -s -w "%{http_code}\n" https://www.netflix.com/sg-zh/title/70143836)
+        if [ "$response" -ne 200 ]; then
+            echo "Error: HTTP response is not 200"
+            exit 1
+        fi
+    - name: Check Openai HTTP
+      run: |
+            response=$(curl -o /dev/null -s -w "%{http_code}\n" https://android.chat.openai.com)
+            if [ "$response" -ne 403 ]; then
+                echo "Error: HTTP response is not 403"
+                exit 1
+            fi
 
     - name: Copy files to S3 with the AWS CLI
       run: |
